
SELECT
"MAPPED_TYPE",
"CONSOLIDATED_BILLING_NUMBER",
"INVOICE_NUMBER",
"RECEIPT_NUMBER",
"INVOICE_DATE",
"CURRENCY",
"OPEN_AMOUNT",
"ORIGINAL_AMOUNT",
(ORIGINAL_AMOUNT-OPEN_AMOUNT) AS "MAPPED_AMOUNT",
"OUTSTANDING_DAYS",
"AGING_BUCKET",
"WON",
"PROJECT_NAME",
"TEMPLATE_FILE",
"UPLOADEDON",
"MODIFIEDON"
FROM "PUBLIC"."T_TRIMATRIX_REPORT"
--WHERE RECEIPT_NUMBER =0
ORDER BY MAPPED_TYPE
;




select   C.INVOICE_NUMBER,C.RECEIPT_NUMBER,T.INVOICE_NUMBER,T.ORIGINAL_AMOUNT,C.ALLOCATED_AMOUNT,C.APPLIED_RECEIPT_AMOUNT,T.INVOICE_DATE  from  T_COLLECTION_REPORT C 
RIGHT  JOIN T_TRIMATRIX_REPORT T
ON  T.INVOICE_NUMBER = C.INVOICE_NUMBER
AND T.MAPPED_TYPE='Invoice'
AND T.RECEIPT_NUMBER =0
AND T.AGING_BUCKET <> 'UNAPPLIED'
ORDER BY C.RECEIPT_NUMBER NULLS LAST ,T.INVOICE_DATE;