CREATE TABLE PUBLIC.T_COLLECTION_REPORT (
	CUSTOMER_NAME VARCHAR(50),
	RECEIPT_NUMBER BIGINT,
	RECEIPT_DATE DATE,
	RECEIPT_CURRENCY VARCHAR(5),
	ALLOCATED_AMOUNT DECIMAL(25,4),
	RECEIVED_AMOUNT DECIMAL(25,4),
	APPLIED_DATE DATE,
	INVOICE_NUMBER VARCHAR(50),
	INVOICE_DATE DATE,
	WON DECIMAL(15,0),
	INVOICE_CURRENCY VARCHAR(5),
	APPLIED_INVOICE_AMOUNT DECIMAL(25,4),
	APPLIED_RECEIPT_AMOUNT DECIMAL(25,4),
	UNAPPLIED_RECEIPT_AMOUNT DECIMAL(25,4),
	COMMENTS VARCHAR(2000),
	CONTRACT_ID VARCHAR(500),
	TEMPLATE_FILE VARCHAR(1000),
	UPLOADEDON TIMESTAMP,
	MODIFIEDON TIMESTAMP NOT NULL,
	RECORDID BIGINT NOT NULL,
	CONSTRAINT T_COLLECTION_REPORT_PK PRIMARY KEY (RECORDID)
) ;
CREATE UNIQUE INDEX PRIMARY_KEY_4 ON PUBLIC.T_COLLECTION_REPORT (RECORDID) ;
