CREATE TABLE PUBLIC.T_COLLECTION_REPORT (
	CUSTOMER_NAME VARCHAR(50),
	RECEIPT_NUMBER BIGINT,
	RECEIPT_DATE DATE,
	RECEIPT_CURRENCY VARCHAR(5),
	ALLOCATED_AMOUNT DECIMAL(25,4),
	RECEIVED_AMOUNT DECIMAL(25,4),
	APPLIED_DATE DATE,
	INVOICE_NUMBER VARCHAR(50),
	INVOICE_DATE DATE,
	WON DECIMAL(15,0),
	INVOICE_CURRENCY VARCHAR(5),
	APPLIED_INVOICE_AMOUNT DECIMAL(25,4),
	APPLIED_RECEIPT_AMOUNT DECIMAL(25,4),
	UNAPPLIED_RECEIPT_AMOUNT DECIMAL(25,4),
	COMMENTS VARCHAR(2000),
	CONTRACT_ID VARCHAR(500),
	TEMPLATE_FILE VARCHAR(1000),
	UPLOADEDON TIMESTAMP,
	MODIFIEDON TIMESTAMP NOT NULL,
	RECORDID BIGINT NOT NULL,
	CONSTRAINT T_COLLECTION_REPORT_PK PRIMARY KEY (RECORDID)
) ;
CREATE UNIQUE INDEX PRIMARY_KEY_5 ON PUBLIC.T_COLLECTION_REPORT (RECORDID) ;
CREATE TABLE "PUBLIC"."T_COLLECTION_REPORT"
(
   CUSTOMER_NAME varchar(50),
   RECEIPT_NUMBER bigint NOT NULL,
   RECEIPT_DATE date,
   RECEIPT_CURRENCY varchar(5),
   ALLOCATED_AMOUNT decimal(25,4),
   RECEIVED_AMOUNT decimal(25,4),
   APPLIED_DATE date,
   INVOICE_NUMBER varchar(50) NOT NULL,
   INVOICE_DATE date,
   WON decimal(15,0),
   INVOICE_CURRENCY varchar(5),
   APPLIED_INVOICE_AMOUNT decimal(25,4),
   APPLIED_RECEIPT_AMOUNT decimal(25,4),
   UNAPPLIED_RECEIPT_AMOUNT decimal(25,4),
   COMMENTS varchar(2000),
   CONTRACT_ID varchar(500),
   TEMPLATE_FILE varchar(1000),
   UPLOADEDON timestamp,
   MODIFIEDON timestamp NOT NULL,
   CONSTRAINT PK_T_COLLECTION_REPORT PRIMARY KEY (RECEIPT_NUMBER,INVOICE_NUMBER)
)
;
CREATE UNIQUE INDEX PRIMARY_KEY_4 ON "PUBLIC"."T_COLLECTION_REPORT"
(
  RECEIPT_NUMBER,
  INVOICE_NUMBER
)
;
