DROP INDEX IDX_T_COLLECTION_REPORT;
DROP TABLE "PUBLIC"."T_COLLECTION_REPORT";

CREATE TABLE "PUBLIC"."T_COLLECTION_REPORT"
(
   
   CUSTOMER_NAME varchar(50),
   RECEIPT_NUMBER bigint NOT NULL,
   RECEIPT_DATE date,
   RECEIPT_CURRENCY varchar(5),
   ALLOCATED_AMOUNT decimal(25,4),
   RECEIVED_AMOUNT decimal(25,4),
   APPLIED_DATE date,
   INVOICE_NUMBER varchar(50) NOT NULL,
   INVOICE_DATE date,
   WON decimal(15,0),
   INVOICE_CURRENCY varchar(5),
   APPLIED_INVOICE_AMOUNT decimal(25,4),
   APPLIED_RECEIPT_AMOUNT decimal(25,4),
   UNAPPLIED_RECEIPT_AMOUNT decimal(25,4),
   COMMENTS varchar(2000),
   CONTRACT_ID varchar(500),
   TEMPLATE_FILE varchar(1000),
   UPLOADEDON timestamp,
   CONSTRAINT PK_T_COLLECTION_REPORT PRIMARY KEY (RECEIPT_NUMBER,INVOICE_NUMBER)
)
;


CREATE UNIQUE INDEX IDX_T_COLLECTION_REPORT ON "PUBLIC"."T_COLLECTION_REPORT"
(
  RECEIPT_NUMBER,
  INVOICE_NUMBER
)
;
