DROP TABLE "PUBLIC"."T_TRIMATRIX_REPORT";

CREATE TABLE "PUBLIC"."T_TRIMATRIX_REPORT"
(
   MAPPED_CUSTOMER varchar(50),
   MAPPED_TYPE varchar(25),
   CONSOLIDATED_BILLING_NUMBER varchar(50),
   INVOICE_NUMBER varchar(50) PRIMARY KEY NOT NULL,
   RECEIPT_NUMBER bigint,
   INVOICE_DATE date,
   CURRENCY varchar(5),
   OPEN_AMOUNT decimal(25,4),
   ORIGINAL_AMOUNT decimal(25,4),
   STATUS varchar(25),
   OUTSTANDING_DAYS decimal(3,0),
   AGING_BUCKET varchar(25),
   WON decimal(15,0),
   PROJECT_NAME varchar(50),
   TEMPLATE_FILE varchar(1000),
   UPLOADEDON timestamp
)
;
CREATE UNIQUE INDEX IDX_TRIMATRIX_REPORT ON "PUBLIC"."T_TRIMATRIX_REPORT"(INVOICE_NUMBER)
;
