CREATE SEQUENCE SEQ_UIDAUTH
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE SEQ_UIDAUTH
  OWNER TO postgres;
  
  CREATE TABLE T_USER_AUTH
(
  ACTIVE boolean NOT NULL DEFAULT false,
  EMAIL character varying(255) NOT NULL,
  PASSWORD character varying(255),
  FIRST_NAME character varying(255),
  UID integer NOT NULL DEFAULT nextval('SEQ_UIDAUTH'::regclass),
  CONSTRAINT PK_USER PRIMARY KEY (EMAIL)
)
WITH (
  OIDS=FALSE
);

ALTER TABLE T_USER_AUTH
  OWNER TO postgres;

CREATE INDEX IDX_USER
  ON T_USER_AUTH
  USING btree
  (EMAIL COLLATE pg_catalog.default, FIRST_NAME COLLATE pg_catalog.default);
  

INSERT INTO T_USER_AUTH(
            UID, ACTIVE, EMAIL, PASSWORD, FIRST_NAME)
    VALUES (DEFAULT, TRUE, 'a@b.com', '123456789', 'TEST');
	
	